mutation resolveContact($operation: String!, $contactUserID: ID!) {
	resolveContact(operation: $operation, contactUserID: $contactUserID) {
		id
		username
		contacts {
			id
			username
			profileImg
		}
	}
}
